# Generated by Django 5.2.6 on 2025-09-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0003_add_location_fields_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
